---
title: "P8130_Final"
output: github_document
date: "2022-12-11"
---

```{r setup, include=FALSE}
library(tidyverse)
library(faraway)
library(glmnet)
library(leaps)
library(caret)
library(readxl)
library(performance)
library(GGally)
```

```{r}
# Import dataset
density_df = read_excel("body_density_data.xlsx")
dat.density = as.data.frame(density_df)
```

```{r}
# Provide descriptive statistics for all variables of interest
dat.density %>% 
  gtsummary::tbl_summary() %>%
  gtsummary::bold_labels()
```

```{r, message=FALSE, warning=FALSE}
# Pairwise association
dat.density %>% 
  select(-id, -bodyfat_siri, -body_density) %>% 
  relocate(`bodyfat_brozek`) %>% 
  ggpairs()
```

```{r}
# Checking normality
hist(sqrt(density_df$age))
hist(1/(density_df$weight))
hist(density_df$height)
hist(log(density_df$neck))
hist(density_df$chest)
hist(density_df$abdomen)
hist(log(density_df$hip))
hist(1/(density_df$thigh))
hist(density_df$knee)
hist(1/(density_df$ankle))
hist(density_df$bicep)
hist(density_df$forearm)
hist(density_df$wrist)
```

```{r}
density_df =
  density_df %>% 
  mutate(
    age = sqrt(age),
    weight = 1/weight,
    neck = log(neck),
    hip = log(hip),
    thigh = 1/thigh,
    ankle = 1/ankle
  )
```

```{r}
# Check for transformation in predictor
mult.fit = lm(bodyfat_brozek ~ age + weight + height + neck + chest + abdomen + hip + thigh + knee + ankle + bicep + forearm + wrist, data = density_df)

par(mfrow = c(2,2))
plot(mult.fit)
```

No transformation needed.

```{r}
# fit regression using all predictors
summary(mult.fit)
```

```{r}
# Model selection
# Backward Elimination
step1 = update(mult.fit, . ~ . -bicep)
summary(step1)
```

```{r}
step2 = update(step1, . ~ . -ankle)
summary(step2)
```

```{r}
step3 = update(step2, . ~ . -knee)
summary(step3)
```

```{r}
step4 = update(step3, . ~ . -thigh)
summary(step4)
```

```{r}
step5 = update(step4, . ~ . -forearm)
summary(step5)
```

```{r}
# Forward Elimination
intercept_only = lm(bodyfat_brozek ~ 1, data = density_df)
step(intercept_only, direction = "forward", scope = formula(mult.fit))
```

```{r}
# Stepwise elimination
step(intercept_only, direction = "both", scope = formula(mult.fit), trace = 0)
```

```{r}
# using cross validation to choose lambda
lambda_seq = 10^seq(-3, 0, by = .1)
set.seed(2022)
cv_object = cv.glmnet(as.matrix(density_df[5:17]), density_df$bodyfat_brozek, lambda = lambda_seq, nfolds = 5)
cv_object
```
```{r}
# Lambda value
cv_object$lambda.min
```

```{r}
# Refit the lasso model with the "best" lambda
fit_bestcv = glmnet(as.matrix(density_df[5:17]), density_df$bodyfat_brozek, lambda = cv_object$lambda.min)

coef(fit_bestcv)
```

```{r}
# Test Based Procedures
mat = as.matrix(density_df)
# Printing the 2 best models of each size, using the Cp criterion:
leaps(x = mat[,5:17], y = mat[,2], nbest = 2, method = "Cp")
```

```{r}
# Printing the 2 best models of each size, using the adjusted R^2 criterion:
leaps(x = mat[,5:17], y = mat[,2], nbest = 2, method = "adjr2")
```

```{r}
# Function regsubsets() performs a subset selection by identifying the "best" model that contains
# a certain number of predictors. By default "best" is chosen using SSE/RSS (smaller is better)
b = regsubsets(bodyfat_brozek ~ age + weight + height + neck + chest + abdomen + hip + thigh + knee + ankle + bicep + forearm + wrist, data = density_df)
rs = summary(b)
```

```{r}
# plot of Cp and Adj-R2 as functions of parameters
par(mfrow=c(1,2))
plot(2:9, rs$cp, xlab="No of parameters", ylab="Cp Statistic")
abline(0,1)
plot(2:9, rs$adjr2, xlab="No of parameters", ylab="Adj R2")
```

```{r}
# Ridge Regression
# fit ridge with specific value for lambda

glmnet(as.matrix(density_df[5:17]), density_df$bodyfat_brozek, lambda = 1, alpha = 0) %>% 
coef()
```

```{r}
# Elastic Net
glmnet(as.matrix(density_df[5:17]), density_df$bodyfat_brozek, lambda = 1, alpha = 0.5) %>% 
coef()
```

```{r}
# Check for violations of regression model assumptions
mult.fitfinal = lm(bodyfat_brozek ~ age + weight + height + neck + chest + abdomen + hip + wrist, data = density_df)
par(mfrow = c(2,2))
plot(mult.fitfinal)
```

```{r}
# MLR for final model
multreg_fat = lm(bodyfat_brozek ~ age + weight + height + neck + chest + abdomen + hip + wrist, data = density_df)
summary(multreg_fat)
anova(multreg_fat)
```

```{r}
# Checking to Outliers and Influential Points
plot(mult.fitfinal, which = 4)
```
```{r}
# remove influential points
fitOut = density_df[-c(39,216),]

# fit model with and without influential points
with = lm(bodyfat_brozek ~ age + weight + height + neck + chest + abdomen + hip + wrist, data = density_df)
without = lm(bodyfat_brozek ~ age + weight + height + neck + chest + abdomen + hip + wrist, data = fitOut)
summary(with); summary(without)

plot(without)
```

```{r}
# Assessing Multicollinearity

# Calculate the variance inflation factor (VIF)
check_collinearity(without)
```


```{r}
# Model validation
set.seed(1)
# Use 5-fold validation and create the training sets
train = trainControl(method = "cv", number = 5)
model_density = train(bodyfat_brozek ~ age + weight + height + neck + chest + abdomen + hip + wrist,
data = density_df,
trControl = train,
method = 'lm',
na.action = na.pass)

model_density$finalModel
print(model_density)
```

